### ISSUE TITLE
lambda 演算那篇博客，add 0 倒数两步是怎么推出来的？

### ISSUE THREAD

**Issue by adispring** [jiacai2050/jiacai2050.github.io#2]
λn2. (λf. λs. s) succ n2 --->
λn2. n2 =
λx. x

**Comment by jiacai2050** [comment]
在`λn2. (λf. λs. s) succ n2 --->` 一步中，`succ` 带入 `f`，`n2` 带入 `s`，然后`λsucc. λn2. n2` 的返回值就是`n2`
